export const AUTH_MODULE_ID = 'AUTH_MODULE_ID';
export const AUTH_SERVICE_OPTIONS = 'AUTH_SERVICE_OPTIONS';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const AUTH_SESSION_SERVICE = 'AUTH_SESSION_SERVICE';
export const AUTH_JWT_SERVICE = 'AUTH_JWT_SERVICE';
export const AUTH_GOOGLE_SERVICE = 'AUTH_GOOGLE_SERVICE';
